# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inici"
  url = ""
  weight = 10

[[main]]
  name = "Masculí"
  url = "/tags/futbol-masculi/"
  weight = 20

[[main]]
  parent = "Masculí"
  name = "La Liga"
  url = "competicions/la-liga/"
  weight = 201

[[main]]
  parent = "Masculí"
  name = "La Liga 2"
  url = "competicions/la-liga-2/"
  weight = 202

[[main]]
  parent = "Masculí"
  name = "Primera RFEF"
  url = "competicions/primera-rfef/"
  weight = 203

[[main]]
  parent = "Masculí"
  name = "Segona RFEF"
  url = "competicions/segona-rfef/"
  weight = 204

[[main]]
  parent = "Masculí"
  name = "Tercera RFEF"
  url = "competicions/tercera-rfef/"
  weight = 205

[[main]]
  name = "Femení"
  url = "/tags/futbol-femeni/"
  weight = 30

[[main]]
  parent = "Femení"
  name = "Primera"
  url = "competicions/primera/"
  weight = 301

[[main]]
  parent = "Femení"
  name = "Segona Pro"
  url = "competicions/segona-pro/"
  weight = 302

[[main]]
  parent = "Femení"
  name = "Primera Nacional"
  url = "competicions/primera-nacional/"
  weight = 303

[[main]]
  name = "Explora les Dades"
  url = "/explora/"
  weight = 50





# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
