# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inici"
  url = ""
  weight = 10

[[main]]
  name = "Primera Masculina"
  url = "tags/la-liga/"
  weight = 15

[[main]]
  name = "Primera Femenina"
  url = "tags/lliga-femenina/"
  weight = 20

[[main]]
  name = "Segona A"
  url = "tags/segona-a/"
  weight = 25

[[main]]
  name = "Segona B"
  url = "tags/segona-b/"
  weight = 30

[[main]]
  name = "Tercera"
  url = "tags/tercera/"
  weight = 40

[[main]]
  name = "Primera Catalana"
  url = "tags/primera-catalana/"
  weight = 50




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
