---
date: "2020-02-14"
external_link: null
image:
  caption: 
  focal_point: Smart
  preview_only: true
summary: Projecció del primera fase de 2020-2021
subtitle: Projecció del primera fase de 2020-2021
tags:
- 2020-2021
- Masculina
title: Primera Catalana
---
### Subgrup 1-A

```{r echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(kableExtra))
teamnames <- read.csv("~/Google Drive/Futbol/teamlist.csv")
data <- read.csv("~/Google Drive/Futbol/data_tables.csv")
table <- data %>% filter(league == 'primera_catalana_1')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-fullname,-shortname, -league, -type2, -type3, -typex, -linkteam)
kable(table, digits = 1, align = 'lcccccc', row.names = FALSE, col.names = c('Club', 'Punts', 'GD', 'Campió', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Projecció de la Classificació' = 1, 'Projecció' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```

### Subgrup 1-B

```{r echo=F,warning=FALSE,message=FALSE}
table <- data %>% filter(league == 'primera_catalana_2')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-fullname,-shortname, -league, -type2, -type3, -typex, -linkteam)
kable(table, digits = 1, align = 'lcccccc', row.names = FALSE, col.names = c('Club', 'Punts', 'GD', 'Campió', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Projecció de la Classificació' = 1, 'Final' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```

### Subgrup 2-A

```{r echo=F,warning=FALSE,message=FALSE}
table <- data %>% filter(league == 'primera_catalana_3')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-fullname,-shortname, -league, -type2, -type3, -typex, -linkteam)
kable(table, digits = 1, align = 'lcccccc', row.names = FALSE, col.names = c('Club', 'Punts', 'GD', 'Campió', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Projecció de la Classificació' = 1, 'Final' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```

### Subgrup 2-B

```{r echo=F,warning=FALSE,message=FALSE}
table <- data %>% filter(league == 'primera_catalana_4')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-fullname,-shortname, -league, -type2, -type3, -typex, -linkteam)
kable(table, digits = 1, align = 'lcccccc', row.names = FALSE, col.names = c('Club', 'Punts', 'GD', 'Campió', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Projecció de la Classificació' = 1, 'Final' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```
