---
date: "2020-02-15"
external_link: null
image:
  caption: 
  focal_point: Smart
  preview_only: true
summary: Projecció del segon fase de 2020-2021
subtitle: Projecció del segon fase de 2020-2021
tags:
- 2020-2021
- Masculina
title: Segona B, Grup III
---
 | [Trajectòria dels equips](/competicions/segona-b-trajectoria/) |
<br>

### Per Ascens a Segona

```{r echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(kableExtra))
teamnames <- read.csv("~/Google Drive/Futbol/teamlist.csv")
data <- read.csv("~/Google Drive/Futbol/data_tables.csv")
table <- data %>% filter(league == 'segunda_b_ascenso_segunda')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-shortname,-fullname,-linkteam, -league,-typex,-type2,-type3)
kable(table, digits = 1, align = 'lccccc', row.names = FALSE, col.names = c('Club', 'Coef.', 'GD', 'Ascens', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Primer Fase de 2020-2021' = 1, 'Projecció' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```

### Per Ascens a Primera RFEF

```{r echo=F,warning=FALSE,message=FALSE}
table <- data %>% filter(league == 'segunda_b_fase_primera_division_rfef')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-shortname,-fullname,-linkteam, -league,-typex,-type2,-type3)
kable(table, digits = 1, align = 'lccccc', row.names = FALSE, col.names = c('Club', 'Coef.', 'GD', 'Ascens', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Primer Fase de 2020-2021' = 1, 'Projecció' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```

### Per Permanència (Segona RFEF)

```{r echo=F,warning=FALSE,message=FALSE}
table <- data %>% filter(league == 'segunda_b_fase_permanencia_segunda_rfef')
table <- teamnames %>% left_join(table, by = "team") %>% arrange(desc(proj.points))
table <- table[complete.cases(table),]
table$linkteam <- iconv(table$fullname,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "-", table$linkteam)
table$team <- paste0("[", table$shortname, "](/clubs/", table$linkteam,"-",table$league,")")
table <- table %>% select(-shortname,-fullname,-linkteam, -league,-typex,-type2,-type3)
kable(table, digits = 1, align = 'lccccc', row.names = FALSE, col.names = c('Club', 'Coef.', 'GD', 'Perm.', 'Favor', 'Contra', 'Qualitat')) %>% add_header_above(c('Primer Fase de 2020-2021' = 1, 'Projecció' = 2, 'Prob. (%)' = 1, 'xGols' = 3)) %>% column_spec(1, bold = T) %>% column_spec(3, border_right = T) %>% column_spec(4, border_right = T)
```
