---
date: "2020-04-01"
title: "Fuenlabrada"
subtitle: "Segona A"
summary: "Segona A"
---
## Evolució dels punts projectats
```{r fig.width=8, fig.height=5, echo=F,warning=FALSE,message=FALSE}
library(tidyverse)
library(ggplot2)
league <- "sega"
teamname <- "Fuenlabrada"
level2 <- 6
level3 <- 18
level2value <- "Playoffs"
adjustment <- 0
table <- read.csv(paste0("~/Google Drive/Futbol/final-",league,".csv"))
prog <- read.csv(paste0("~/Google Drive/Futbol/prog-",league,".csv"))
level1points <- (table$proj.points[1]+table$proj.points[2])/2
level2points <- (table$proj.points[level2]+table$proj.points[level2+1])/2
level3points <- (table$proj.points[level3]+table$proj.points[level3+1])/2
prog <- prog %>% subset(team == teamname)
prog$points <- prog$points + adjustment
level1df <- NA
level1df <- data.frame(level1df, team = rep("Campió", each = nrow(prog)))
level1df <- data.frame(level1df, points = rep(level1points, each = nrow(prog)))
level1df <- data.frame(level1df, round = rep(min(prog$round):max(prog$round), each = 1))
level1df <- level1df %>% select(-level1df)
level2df <- NA
level2df <- data.frame(level2df, team = rep(level2value, each = nrow(prog)))
level2df <- data.frame(level2df, points = rep(level2points, each = nrow(prog)))
level2df <- data.frame(level2df, round = rep(min(prog$round):max(prog$round), each = 1))
level2df <- level2df %>% select(-level2df)
level3df <- NA
level3df <- data.frame(level3df, team = rep("Descens", each = nrow(prog)))
level3df <- data.frame(level3df, points = rep(level3points, each = nrow(prog)))
level3df <- data.frame(level3df, round = rep(min(prog$round):max(prog$round), each = 1))
level3df <- level3df %>% select(-level3df)
prog <- rbind(prog, level1df)
prog <- rbind(prog, level2df)
prog <- rbind(prog, level3df)
p <- ggplot(data=prog) + geom_line(aes(round,points, color = team))
p + theme_minimal() + labs(color = "", x = "Jornada", y = "Punts Projectats")
```
 
## Pròxims partits
```{r echo=F,warning=FALSE,message=FALSE}
library(kableExtra)
games <- read.csv(paste0("~/Google Drive/Futbol/games-",league,".csv"))
games <- games %>% subset(team1 == teamname | team2 == teamname)
kable(games, digits = 1, align = "c", row.names = FALSE, col.names = c("Jornada", "Equip", "Guanyar", "Empatar", "Guanyar", "Equip")) %>% kable_styling(bootstrap_options = c("hover", "responsive"), fixed_thead = T) %>% add_header_above(c("2019-20" = 1, "Local" = 2, " " = 1, "Visitant" = 2)) %>% column_spec(2, bold = T, color = "#303030") %>% column_spec(6, bold = T, color = "#303030")
```
