---
date: "2021-01-01"
title: "Reyer Venècia"
subtitle: "EuroLeague"
summary: "EuroLeague"
---
 
### Classificació projectada
```{r, hist, fig.width=8, fig.height=3, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
hist <- readRDS('~/Google Drive/Futbol/basket_hists_euro.rds') %>% filter(team == 'venezia')
p <- ggplot(hist, aes(as.factor(rank))) + geom_bar(fill = "#f66f5c")
p + theme_minimal() + labs(y = "Simulacions", x = "Classificació") + theme(axis.text.y=element_blank())
```
 
### Pròxims partits
```{r, partits, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(kableExtra))
home <- readRDS('~/Google Drive/Futbol/basket_odds_euro.rds') %>% arrange(away) %>% filter(home == 'venezia')
away <- readRDS('~/Google Drive/Futbol/basket_odds_euro.rds') %>% arrange(home) %>% filter(away == 'venezia')
games <- bind_rows(home,away) %>% select(-home,-away)
kable(games, align = "c", row.names = FALSE, col.names = c("Equip", "Guanyar %", "Guanyar", "Equip")) %>% add_header_above(c("Local" = 2, "Visitant" = 2)) %>% column_spec(1, bold = T) %>% column_spec(4, bold = T)
```
