---
date: "2021-01-01"
title: "Sevilla FC"
subtitle: 'La Liga F'
summary: 'La Liga F'
---
```{r, traj, fig.width=8, fig.height=4, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
traj <- readRDS('~/GoogleDrive/Futbol/futstat_trajs.rds') %>% filter(team == '/Sevilla-Fc-Femenino-Esp') %>% filter(date > as.POSIXct('2021-08-01'))

if (nrow(traj) > 2){
  table <- readRDS('~/GoogleDrive/Futbol/futstat_tables.rds') %>% filter(league == 'primera_division_femenina_1')
  league <- readRDS('~/GoogleDrive/Futbol/ligas.rds') %>% filter(league == 'primera_division_femenina' & group == 1)
  t1.line <- (table$pts[league$t1.max] + table$pts[league$t1.max+1])/2
  t2.line <- (table$pts[league$t2.max] + table$pts[league$t2.max+1])/2
  des.line <- (table$pts[league$des.min] + table$pts[league$des.min-1])/2
  p <- traj %>% mutate(Timestamp = date, Points = pts) %>% ggplot() + geom_line(aes(Timestamp,Points, group = 1), linewidth = 1.5, color = '#f66f5c') + geom_hline(aes(yintercept=t1.line), linetype='dashed', color='#dbdbdb') + annotate('text',min(traj$date),t1.line,label = 'Campió', vjust = -.5, hjust = 'left', color='#5c5c5c') + geom_hline(aes(yintercept=t2.line), linetype='dashed', color='#dbdbdb') + annotate('text',min(traj$date),t2.line,label = 'UCL', vjust = -.5, hjust = 'left', color='#5c5c5c') + geom_hline(aes(yintercept=des.line), linetype='dashed', color='#dbdbdb') + annotate('text',min(traj$date),des.line,label = 'Descens', vjust = -.5, hjust = 'left', color='#5c5c5c')
  plotly::ggplotly(p + theme_minimal() + labs(x = "Temporada", y = "Punts Projectats") + theme(axis.text.x=element_blank()), tooltip = c("Timestamp","Points"))
}
```

### Classificació projectada
```{r, hist, fig.width=8, fig.height=3, echo=F,warning=FALSE,message=FALSE}
hist <- readRDS('~/GoogleDrive/Futbol/futstat_hists.rds') %>% filter(team == '/Sevilla-Fc-Femenino-Esp')
p <- hist %>% mutate(Classification = as.factor(rank)) %>% ggplot(aes(Classification)) + geom_bar(fill = "#f66f5c")
plotly::ggplotly(p + theme_minimal() + labs(y = "Simulacions", x = "Classificació") + theme(axis.text.y=element_blank()))

```

### Pròxims partits
```{r, partits, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(kableExtra))
teamnames <- readRDS("~/GoogleDrive/Futbol/teamlist.rds") %>% select(-fullname) %>% rename(team1 = team, shortname1 = shortname)
games <- readRDS('~/GoogleDrive/Futbol/futstat_odds.rds')  %>% filter(team1 == '/Sevilla-Fc-Femenino-Esp' | team2 == '/Sevilla-Fc-Femenino-Esp') %>% left_join(teamnames, by = 'team1') %>% left_join(teamnames %>% rename(team2 = team1, shortname2 = shortname1), by = 'team2') %>% select(shortname1,p1,pd,p2,shortname2) %>% mutate(p1 = p1*100, pd = pd*100, p2 = p2*100)
if(nrow(games)>0){kable(games, digits = 1, align = "c", row.names = FALSE, col.names = c("Equip", "Guanyar", "Empatar", "Guanyar", "Equip")) %>% add_header_above(c("Local" = 2, "(%)" = 1, "Visitant" = 2)) %>% column_spec(1, bold = T) %>% column_spec(5, bold = T)}
```
