---
date: "2020-06-17"
title: "UD Almeria"
subtitle: 'Segona A'
summary: 'Segona A'
---
```{r fig.width=8, fig.height=5, echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
d <- read.csv('~/Google Drive/Futbol/data_trajectories.csv') %>% filter(team == '/Almeria')
h <- read.csv('~/Google Drive/Futbol/data_tables.csv') %>% filter(league == 'segunda')
type1 <- as.numeric(h[2,2] + h[3,2])/2
type2 <- as.numeric(h[7,2] + h[6,2])/2
type3 <- as.numeric(h[18,2] + h[19,2])/2
p <- ggplot(data=d) + geom_line(aes(round,points), size = 1.5, color = 'blue') + geom_hline(aes(yintercept=type1), linetype='dashed', color='#5c5c5c') + annotate('text',0,type1,label = 'Ascens', vjust = -.5, hjust = 'left', color='#5c5c5c') + geom_hline(aes(yintercept=type2), linetype='dashed', color='#5c5c5c') + annotate('text',0,type2,label = 'Playoffs', vjust = -.5, hjust = 'left', color='#5c5c5c') + geom_hline(aes(yintercept=type3), linetype='dashed', color='#5c5c5c') + annotate('text',0,type3,label = 'Descens', vjust = -.5, hjust = 'left', color='#5c5c5c')
if (nrow(d)>10){p + theme_minimal() + labs(x = "Jornada", y = "Punts Projectats")}
```
 
### Pròxims partits
```{r echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(kableExtra))
teamnames <- read.csv("~/Google Drive/Futbol/teamlist.csv") %>% select(-fullname)
games <- read.csv("~/Google Drive/Futbol/data_games.csv")
games <- games %>% filter(team1 == '/Almeria' | team2 == '/Almeria')
if (nrow(games>0)){names(teamnames) <- c("home", "team1")
games <- games %>% left_join(teamnames, by = "team1")
names(teamnames) <- c("away", "team2")
games <- games %>% left_join(teamnames, by = "team2") %>% select(jornada, home, p1, pd, p2, away)
kable(games, digits = 1, align = "c", row.names = FALSE, col.names = c("Jornada", "Equip", "Guanyar", "Empatar", "Guanyar", "Equip")) %>% add_header_above(c("2019-20" = 1, "Local" = 2, "(%)" = 1, "Visitant" = 2)) %>% column_spec(2, bold = T) %>% column_spec(6, bold = T)}
```
