---
date: "2020-06-17"
title: COVID-19
subtitle: Gràfics del coronavirus a Catalunya
summary: Gràfics del coronavirus a Catalunya
---
## Catalunya
```{r echo=F,warning=FALSE,message=FALSE}
library(tidyverse)
library(plotly)
library(data.table)
options(dplyr.summarise.inform=F)
data <- read_csv("https://analisi.transparenciacatalunya.cat/api/views/xuwf-dxjd/rows.csv", col_types = cols())
data$date <- as.Date(data$TipusCasData, format = "%d/%m/%Y")
update <- read_csv("~/Google Drive/Futbol/updateinfo.csv")
updaterow <- tibble(Sys.time(), nrow(data))
update[(nrow(update)+1),] <- updaterow
write_csv(update, "~/Google Drive/Futbol/updateinfo.csv")
cat <- data %>% filter(TipusCasDescripcio == "Positiu PCR") %>% filter(!RegioSanitariaDescripcio == "No classificat") %>% group_by(date) %>% summarise(cases = sum(NumCasos)) 
zeros <- data.frame(c(as.Date("2020-02-20"),as.Date("2020-02-21"),as.Date("2020-02-22"),as.Date("2020-02-23"),as.Date("2020-02-24"),as.Date("2020-02-25"),as.Date("2020-02-26"),as.Date("2020-02-27"),as.Date("2020-03-01"),as.Date("2020-03-03")))
zeros$cases <- 0
names(zeros) <- names(cat)
cat <- rbind(zeros, cat)
cat <- cat %>% arrange(date) %>% mutate(casos = frollmean(cases, 7)) %>% arrange(desc(date))

p0 <- ggplot(cat) + geom_line(aes(date, casos), color = "red") + theme_minimal() + geom_vline(aes(xintercept=as.numeric(as.Date("2020-05-04"))), linetype='dashed', color='lightgrey') + geom_vline(aes(xintercept=as.numeric(as.Date("2020-06-19"))), linetype='dashed', color='lightgrey') + labs(x = "", y = "Mitjana de casos a 7 dies")
p0 <- ggplotly(p0, width=875, height=600)
p0 <- config(p0, displayModeBar = FALSE)
p0
```
## Regió Sanitària
```{r echo=F,warning=FALSE,message=FALSE}
by_region <- data %>% filter(TipusCasDescripcio == "Positiu PCR") %>% filter(!RegioSanitariaDescripcio == "No classificat") %>% group_by(date, RegioSanitariaDescripcio) %>% summarise(cases = sum(NumCasos)) 
zero.dates <- unique(by_region$date)
zero.dates <- zero.dates[1:(length(zero.dates)-1)]
zero.dates <- unique(c(as.Date("2020-02-22"),as.Date("2020-02-23"),as.Date("2020-02-24"),as.Date("2020-02-25"),as.Date("2020-02-26"),as.Date("2020-02-27"),as.Date("2020-02-28"),as.Date("2020-03-01"),as.Date("2020-03-02"),as.Date("2020-03-03"),as.Date("2020-03-04"), zero.dates))
places <- unique(by_region$RegioSanitariaDescripcio)
zeros <- data.frame(zero.dates,rep(places, each = length(zero.dates)))
zeros$cases <- 0
names(zeros) <- names(by_region)
by_region <- rbind(by_region, zeros)
by_region <- by_region %>% group_by(date, RegioSanitariaDescripcio) %>% summarise(cases = sum(cases)) %>% arrange(date)
by_region <- by_region %>% group_by(RegioSanitariaDescripcio) %>% mutate(casos = frollmean(cases, 7)) %>% arrange(desc(date))
names(by_region)[2] <- "regio"
names(by_region)[1] <- "data"

p1 <- ggplot(by_region) + geom_line(aes(data, casos, color = regio)) + theme_minimal() + geom_vline(aes(xintercept=as.numeric(as.Date("2020-05-04"))), linetype='dashed', color='lightgrey') + geom_vline(aes(xintercept=as.numeric(as.Date("2020-06-19"))), linetype='dashed', color='lightgrey') + labs(x = "", y = "Mitjana de casos a 7 dies", color = "")
p1 <- ggplotly(p1, width=875, height=600)
p1 <- config(p1, displayModeBar = FALSE)
p1
```
<br>

## Districte de Barcelona
```{r echo=F,warning=FALSE,message=FALSE}
by_district <- data %>% filter(TipusCasDescripcio == "Positiu PCR") %>% filter(str_detect(SectorSanitariDescripcio, 'Barcelona')) %>% group_by(date, SectorSanitariDescripcio) %>% summarise(cases = sum(NumCasos)) 
zero.dates <- unique(by_district$date)
zero.dates <- zero.dates[1:(length(zero.dates)-1)]
zero.dates <- unique(c(as.Date("2020-02-24"),as.Date("2020-02-25"),as.Date("2020-02-26"),as.Date("2020-02-27"),as.Date("2020-02-28"),as.Date("2020-03-01"),as.Date("2020-03-02"),as.Date("2020-03-03"),as.Date("2020-03-04"),as.Date("2020-03-06"),as.Date("2020-03-08"), zero.dates))
places <- unique(by_district$SectorSanitariDescripcio)
zeros <- data.frame(zero.dates,rep(places, each = length(zero.dates)))
zeros$cases <- 0
names(zeros) <- names(by_district)
by_district <- rbind(by_district, zeros)
by_district <- by_district %>% group_by(date, SectorSanitariDescripcio) %>% summarise(cases = sum(cases)) %>% arrange(date)
by_district <- by_district %>% group_by(SectorSanitariDescripcio) %>% mutate(casos = frollmean(cases, 7)) %>% arrange(desc(date))
names(by_district)[2] <- "districte"
by_district$districte <- str_sub(by_district$districte,10,-1)
names(by_district)[1] <- "data"

p2 <- ggplot(by_district) + geom_line(aes(data, casos, color = districte)) + theme_minimal() + geom_vline(aes(xintercept=as.numeric(as.Date("2020-05-04"))), linetype='dashed', color='lightgrey') + geom_vline(aes(xintercept=as.numeric(as.Date("2020-06-19"))), linetype='dashed', color='lightgrey') + labs(x = "", y = "Mitjana de casos a 7 dies", color = "")
p2 <- ggplotly(p2, width=875, height=600)
p2 <- config(p2, displayModeBar = FALSE)
p2
```