---
date: "2020-06-17"
image:
  preview_only: true
summary: Projecció de 2021
tags:
  - Altres Esports
title: European League of Football
---
## Nord
```{r echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(kableExtra))
suppressMessages(library(stringr))
table <- read.csv("~/Google Drive/Futbol/elf_table.csv") %>% filter(div == "north") %>% select(-div) 
table$linkteam <- iconv(table$team,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "_", table$linkteam)
table$team <- paste0("[", table$team, "](/clubs/", table$linkteam,"_elf)")
table <- table %>% select(-linkteam)
kable(table, digits = 1, align = 'lccccc', row.names = FALSE, col.names = c('Club', 'Elo', '1a', '2a', '3a', '4a')) %>% add_header_above(c('Projecció de la Classificació' = 2, 'Probabilitat (%)' = 4)) %>% column_spec(1, bold = T) %>% column_spec(2, border_right = T)
```

## Sud
```{r echo=F,warning=FALSE,message=FALSE}
suppressMessages(library(dplyr))
suppressMessages(library(kableExtra))
suppressMessages(library(stringr))
table <- read.csv("~/Google Drive/Futbol/elf_table.csv") %>% filter(div == "south") %>% select(-div) 
table$linkteam <- iconv(table$team,to="ASCII//TRANSLIT")
table$linkteam <- tolower(gsub("[[:punct:]]", "", table$linkteam))
table$linkteam <- gsub("[[:space:]]", "_", table$linkteam)
table$team <- paste0("[", table$team, "](/clubs/", table$linkteam,"_elf)")
table <- table %>% select(-linkteam)
kable(table, digits = 1, align = 'lccccc', row.names = FALSE, col.names = c('Club', 'Elo', '1a', '2a', '3a', '4a')) %>% add_header_above(c('Projecció de la Classificació' = 2, 'Probabilitat (%)' = 4)) %>% column_spec(1, bold = T) %>% column_spec(2, border_right = T)
```
